// Grid-based coordinates for a 20x10 grid representing the world map
export const CITY_COORDINATES: Record<string, { row: number; col: number }> = {
    'Unknown': { row: 5, col: 10 },
    'London': { row: 3, col: 10 },
    'Sydney': { row: 8, col: 18 },
    'New York': { row: 4, col: 4 },
    'Addis Ababa, Ethiopia': { row: 5, col: 11 },
    'Toronto': { row: 4, col: 4 },
    'Berlin': { row: 3, col: 10 },
    'Paris': { row: 3, col: 9 },
    'Tokyo': { row: 4, col: 17 },
    'Mumbai': { row: 5, col: 14 },
    'Beijing': { row: 4, col: 16 },
    'São Paulo': { row: 7, col: 5 },
    'Mexico City': { row: 5, col: 3 },
    'Cairo': { row: 5, col: 11 },
    'Moscow': { row: 3, col: 13 },
    'Seoul': { row: 4, col: 16 },
    'Jakarta': { row: 6, col: 15 },
    'Istanbul': { row: 4, col: 11 },
    'Amsterdam': { row: 3, col: 10 },
    'Riyadh': { row: 5, col: 12 },
    'Dubai': { row: 5, col: 12 },
    'Singapore': { row: 6, col: 15 },
    'Hong Kong': { row: 5, col: 16 },
    'Los Angeles': { row: 4, col: 2 },
    'Chicago': { row: 4, col: 3 },
    'Bangkok': { row: 5, col: 15 },
    'Johannesburg': { row: 7, col: 11 },
    'Lagos': { row: 6, col: 9 },
    'Buenos Aires': { row: 7, col: 4 },
    'Lima': { row: 6, col: 3 },
    'Madrid': { row: 3, col: 9 },
    'Rome': { row: 4, col: 10 },
    'Vienna': { row: 3, col: 10 },
    'Stockholm': { row: 2, col: 10 },
    'Athens': { row: 4, col: 11 },
    'Warsaw': { row: 3, col: 11 },
    'Prague': { row: 3, col: 10 },
    'Budapest': { row: 3, col: 11 },
    'Zurich': { row: 3, col: 10 },
    'Dublin': { row: 3, col: 9 },
    'Lisbon': { row: 3, col: 8 },
    'Copenhagen': { row: 2, col: 10 },
    'Helsinki': { row: 2, col: 11 },
    'Oslo': { row: 2, col: 10 },
    'Brussels': { row: 3, col: 10 },
    'Luxembourg': { row: 3, col: 10 },
    'Monaco': { row: 3, col: 9 },
    'Vaduz': { row: 3, col: 10 },
    'San Marino': { row: 4, col: 10 },
    'Vatican City': { row: 4, col: 10 },
    'Andorra la Vella': { row: 3, col: 9 },
    'Skopje': { row: 4, col: 11 },
    'Tirana': { row: 4, col: 11 },
    'Valletta': { row: 4, col: 11 },
    'Sofia': { row: 4, col: 11 },
    'Bucharest': { row: 4, col: 11 },
    'Belgrade': { row: 4, col: 11 },
    'Sarajevo': { row: 4, col: 11 },
    'Podgorica': { row: 4, col: 11 },
    'Pristina': { row: 4, col: 11 },
    'Zagreb': { row: 4, col: 10 },
    'Ljubljana': { row: 4, col: 10 },
    'Bratislava': { row: 3, col: 11 },
    'Vilnius': { row: 3, col: 12 },
    'Riga': { row: 3, col: 11 },
    'Tallinn': { row: 2, col: 11 },
    'Minsk': { row: 3, col: 12 },
    'Kiev': { row: 3, col: 12 },
    'Chisinau': { row: 4, col: 11 },
    'Tbilisi': { row: 4, col: 12 },
    'Yerevan': { row: 4, col: 12 }
};

// Country flag emojis
export const COUNTRY_FLAGS: Record<string, string> = {
    'Unknown': '🌐',
    'London': '🇬🇧',
    'Sydney': '🇦🇺',
    'New York': '🇺🇸',
    'Addis Ababa, Ethiopia': '🇪🇹',
    'Toronto': '🇨🇦',
    'Berlin': '🇩🇪',
    'Paris': '🇫🇷',
    'Tokyo': '🇯🇵',
    'Mumbai': '🇮🇳',
    'Beijing': '🇨🇳',
    'São Paulo': '🇧🇷',
    'Mexico City': '🇲🇽',
    'Cairo': '🇪🇬',
    'Moscow': '🇷🇺',
    'Seoul': '🇰🇷',
    'Jakarta': '🇮🇩',
    'Istanbul': '🇹🇷',
    'Amsterdam': '🇳🇱',
    'Riyadh': '🇸🇦',
    'Dubai': '🇦🇪',
    'Singapore': '🇸🇬',
    'Hong Kong': '🇭🇰',
    'Los Angeles': '🇺🇸',
    'Chicago': '🇺🇸',
    'Bangkok': '🇹🇭',
    'Johannesburg': '🇿🇦',
    'Lagos': '🇳🇬',
    'Buenos Aires': '🇦🇷',
    'Lima': '🇵🇪',
    'Madrid': '🇪🇸',
    'Rome': '🇮🇹',
    'Vienna': '🇦🇹',
    'Stockholm': '🇸🇪',
    'Athens': '🇬🇷',
    'Warsaw': '🇵🇱',
    'Prague': '🇨🇿',
    'Budapest': '🇭🇺',
    'Zurich': '🇨🇭',
    'Dublin': '🇮🇪',
    'Lisbon': '🇵🇹',
    'Copenhagen': '🇩🇰',
    'Helsinki': '🇫🇮',
    'Oslo': '🇳🇴',
    'Brussels': '🇧🇪',
    'Luxembourg': '🇱🇺',
    'Monaco': '🇲🇨',
    'Vaduz': '🇱🇮',
    'San Marino': '🇸🇲',
    'Vatican City': '🇻🇦',
    'Andorra la Vella': '🇦🇩',
    'Skopje': '🇲🇰',
    'Tirana': '🇦🇱',
    'Valletta': '🇲🇹',
    'Sofia': '🇧🇬',
    'Bucharest': '🇷🇴',
    'Belgrade': '🇷🇸',
    'Sarajevo': '🇧🇦',
    'Podgorica': '🇲🇪',
    'Pristina': '🇽🇰',
    'Zagreb': '🇭🇷',
    'Ljubljana': '🇸🇮',
    'Bratislava': '🇸🇰',
    'Vilnius': '🇱🇹',
    'Riga': '🇱🇻',
    'Tallinn': '🇪🇪',
    'Minsk': '🇧🇾',
    'Kiev': '🇺🇦',
    'Chisinau': '🇲🇩',
    'Tbilisi': '🇬🇪',
    'Yerevan': '🇦🇲'
};